<?php
// This file has been automatically generated by LocalSettingsGenerator.php
// Do NOT EDIT this block
if ( !defined( 'ENTRY_POINT' ) ) {
    die( 'This is not an entry point. LocalSettings' );
}
// You can edit settings from here
